cache: apt
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - subversion
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy pandas cython
  - pip install pytest-pep8 pytest-cov python-coveralls c3d
  - ( cd ode ; ./build-ode.sh )
  - pip install .
script:
  - LD_LIBRARY_PATH=$VIRTUAL_ENV/lib:$LD_LIBRARY_PATH py.test -v --pep8 --cov=pagoda --cov-report=term-missing
after_success:
  - coveralls
